### ISSUE TITLE
Internal Server Error after registration

### ISSUE THREAD

**Issue by stuartduncan416** [ccs-amsterdam/3bij3#13]
After filling out the form here: 

https://tux02ascor.fmg.uva.nl/3bij3/en/register

and then pressing the register button, I receive an Internal Server Error. I have attached a screenshot of the page. 

Just curious, should the system be useable outside of the UvA campus ?  

![error](https://user-images.githubusercontent.com/48373359/208443073-514f83b0-9844-4526-8fcb-fdbae8ea7df8.jpg)

**Comment by damian0604** [comment]
I hope it is fixed now by #14 , and it should at the moment be open to the world

**Comment by stuartduncan416** [comment]
Appears to be fixed I had to issues accessing the site.
