### ISSUE TITLE
Add example data

### ISSUE THREAD

**Issue by vanatteveldt** [ccs-amsterdam/3bij3#3]
Create a small script to insert e.g. wikinews data to the elastic database to get going

**Comment by vanatteveldt** [comment]
See https://github.com/ccs-amsterdam/3bij3/commit/aaed4bf983abe866f6dee767203998f58888f729

Todo: (1) test in 3bij3, (2) add instructions to readme

**Comment by damian0604** [comment]
closed, solved with the added script to scrape and insert data
